### ISSUE TITLE
Invalid token page

### ISSUE THREAD

**Issue by JMKassman** [crosenblatt/hello-mentors#24]
I need something like this: 
![image](https://user-images.githubusercontent.com/7897446/56165350-b5bd5100-5fa0-11e9-927c-7a33af39c2f7.png)
for when the token is invalid

**Comment by crosenblatt** [comment]
This is on the page that comes after they click the email link?

**Comment by JMKassman** [comment]
Yes

**Comment by crosenblatt** [comment]
token valid
